package pki

import (
	"bytes"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/asn1"
	"encoding/json"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"
)

// Certificate size and structure limit constants (aligned with v1.7.1 spec and patent specification).
const (
	// MaxCapabilities is the maximum number of AIC.capabilities.
	MaxCapabilities = 256
	// MaxAuthorizationConstraints is the upper limit for the AIC/PA
	// authorizationConstraints count (32).
	// The spec protocol structure limit is 32 (MaxExtensionsSlots);
	// the implementation uses the stricter default recommended value of 8 to ensure certificate size and parsing safety.
	MaxAuthorizationConstraints = 32
	// MaxExtensionsSlots is the maximum capacity of AIC.extensions slots.
	MaxExtensionsSlots = 32
	// MaxGrantEntries is the maximum number of PrincipalAuthorization.grants.
	MaxGrantEntries = 256
	// MaxConstraintParams is the byte limit for a single authorizationConstraints parameters entry.
	MaxConstraintParams = 512
	// MaxCapParams is the byte limit for a single Capability parameters entry.
	MaxCapParams = 4096
	// MaxNonceLen is the fixed length of DelegationAuthorization.nonce (32 bytes).
	MaxNonceLen = 32
	// MaxRequestedLifetime is the upper limit for requestedLifetime (seconds, 86400 = 24h).
	MaxRequestedLifetime = 86400
	// MinRequestedLifetime is the recommended lower limit for requestedLifetime (seconds, 3600 = 1h).
	MinRequestedLifetime = 3600
	// MaxRecommendedCertDERSize is the recommended upper limit for AIC certificate DER size (12KB).
	// Exceeding this value is recommended to split the envelope; 16KB is the hard reject limit in production code (see varwof-core sign.go).
	MaxRecommendedCertDERSize = 12 * 1024
	// MaxHardCertDERSize is the hard reject limit for AIC certificate DER size (16KB).
	MaxHardCertDERSize = 16 * 1024
	// MaxConcurrentMin is the minimum value for the max-concurrent constraint max parameter (spec P1-A-29).
	MaxConcurrentMin = 1
	// MaxConcurrentMax is the maximum value for the max-concurrent constraint max parameter (spec P1-A-29).
	MaxConcurrentMax = 1024
	// ConstraintConcurrentKey is the capabilityId for the max-concurrent constraint.
	ConstraintConcurrentKey = "max-concurrent"
)

// AlgorithmIdentifier is ASN.1 algorithm identifier.
type AlgorithmIdentifier struct {
	Algorithm  asn1.ObjectIdentifier
	Parameters asn1.RawValue `asn1:"optional"`
}

// DelegationMode defines agent delegation mode.
type DelegationMode int

const (
	DelegationAuthorized     DelegationMode = 0
	DelegationRepresentative DelegationMode = 1
)

// ExtField is a single extension field inside AIC extensions slot.
type ExtField struct {
	ExtnID    asn1.ObjectIdentifier `asn1:"objectidentifier"`
	Critical  bool                  `asn1:"default:false"`
	ExtnValue []byte                `asn1:"octet"`
}

// Capability is a protocolized capability container.
//
// Encoding convention (v1.8, unified PA grant / AIC capability convention):
//   - SchemeId  : capability scheme identifier (e.g. "ca", "cert", "varwof/demo-mysql-v1", "varwof-gateway-v1")
//   - CapabilityId : pure action identifier, **without scheme prefix** (e.g. "list", "issue", "SELECT:*")
//   - Full permission identifier = SchemeId + ":" + CapabilityId (e.g. "ca:list", "varwof/demo-mysql-v1:SELECT:*"),
//     uniformly generated by FullID(); all matching/intersection/authorization decisions must use
//     the full identifier; consumers must not concatenate themselves or match authorization policies
//     using bare CapabilityId.
type Capability struct {
	SchemeId     string `json:"scheme_id" asn1:"utf8"`
	CapabilityId string `json:"capability_id" asn1:"utf8"`
	Parameters   []byte `json:"parameters,omitempty" asn1:"optional,omitempty,contextspecific,explicit,tag:0"`
}

// FullID returns the full capability identifier (scheme:capabilityId).
// When SchemeId is empty, it degrades to CapabilityId (for capabilities without a scheme).
// This is the single authoritative concatenation point across the entire system;
// gateway/core/type layers must uniformly reuse this method.
// Modules must not duplicate the concatenation logic.
func (c Capability) FullID() string {
	if c.SchemeId == "" {
		return c.CapabilityId
	}
	return c.SchemeId + ":" + c.CapabilityId
}

// Reason is the delegation authorization reason (v1.7.1, dev-docs/aic/01-asn1.md §Reason).
// Both fields are REQUIRED (MUST be non-empty); reason is a statement for audit/display
// only and does not participate in permission decisions.
type Reason struct {
	ReasonCode  string `asn1:"utf8"`
	Description string `asn1:"utf8"`
}

// DelegationAuthorization is user authorization cryptographic evidence (v1.7.1 spec §3).
// Field order: reason → requestedLifetime → timestamp → nonce → signatureAlgorithm → signatureValue.
type DelegationAuthorization struct {
	Reason             Reason              `asn1:""`
	RequestedLifetime  int                 `asn1:"default:0"`
	Timestamp          time.Time           `asn1:"generalized"`
	Nonce              []byte              `asn1:"octet"`
	SignatureAlgorithm AlgorithmIdentifier `asn1:""`
	SignatureValue     []byte              `asn1:"octet"`
}

// IsPresent checks if DelegationAuthorization is actually set (non-zero).
func (d DelegationAuthorization) IsPresent() bool {
	return d.Reason.ReasonCode != "" || d.Reason.Description != "" ||
		len(d.SignatureValue) > 0 || len(d.Nonce) > 0 ||
		d.RequestedLifetime > 0 || !d.Timestamp.IsZero()
}

// AIC is the X.509v3 extension ASN.1 structure (v1.7.1 spec §AIC).
// delegationAuthorization is REQUIRED per spec; emptiness is enforced at
// parse/validate/sign time. Go encoding/asn1 cannot marshal a mandatory empty
// DelegationAuthorization (nil signature OID), so the tag keeps `optional,omitempty`
// on the wire while the semantics remain required.
type AIC struct {
	Version                  int                     `asn1:"default:1"`
	AgentId                  string                  `asn1:"utf8"`
	PrincipalUid             PrincipalUid            `asn1:""`
	Capabilities             []Capability            `asn1:"sequence"`
	DelegationMode           DelegationMode          `asn1:"default:0"`
	AuthorizationConstraints []Capability            `asn1:"optional,omitempty,contextspecific,explicit,tag:0"`
	DelegationAuthorization  DelegationAuthorization `asn1:"optional,omitempty"`
	Extensions               []ExtField              `asn1:"optional,omitempty,contextspecific,explicit,tag:1"`
}

// DelegationAuthTBS is the to-be-signed data for DelegationAuthorization signature (v1.7.1).
// Field order: version → agentId → principalUid → reason → capabilities → delegationMode →
// authorizationConstraints → requestedLifetime → timestamp → nonce.
type DelegationAuthTBS struct {
	Version                  int            `asn1:"default:1"`
	AgentId                  string         `asn1:"utf8"`
	PrincipalUid             PrincipalUid   `asn1:""`
	Reason                   Reason         `asn1:""`
	Capabilities             []Capability   `asn1:"sequence"`
	DelegationMode           DelegationMode `asn1:"default:0"`
	AuthorizationConstraints []Capability   `asn1:"optional,omitempty,contextspecific,explicit,tag:0"`
	RequestedLifetime        int            `asn1:"default:0"`
	Timestamp                time.Time      `asn1:"generalized"`
	Nonce                    []byte         `asn1:"octet"`
}

// ParseAIC parses the AIC extension from a certificate.
// Per v1.7.1 spec delegationAuthorization is REQUIRED; a present AIC extension
// without a non-empty DelegationAuthorization is rejected.
func ParseAIC(cert *x509.Certificate) (*AIC, error) {
	if cert == nil {
		return nil, nil
	}
	for _, ext := range cert.Extensions {
		if ext.Id.Equal(OIDAIC) {
			var aic AIC
			if _, err := asn1.Unmarshal(ext.Value, &aic); err != nil {
				return nil, fmt.Errorf("aic: unmarshal failed: %w", err)
			}
			if !aic.DelegationAuthorization.IsPresent() {
				return nil, fmt.Errorf("aic: delegationAuthorization is required but missing")
			}
			return &aic, nil
		}
	}
	return nil, nil
}

// Principal returns the human principal represented by the agent.
func (a *AIC) Principal() string {
	if a == nil {
		return ""
	}
	return a.PrincipalUid.String()
}

// HasProtocol checks if agent has the specified schemeId capability.
func (a *AIC) HasProtocol(schemeId string) bool {
	if a == nil {
		return false
	}
	for _, cap := range a.Capabilities {
		if cap.SchemeId == schemeId {
			return true
		}
	}
	return false
}

// CheckPermission checks if agent has the specified capability (full ID,
// glob match). The capability is matched by its FullID (scheme:capabilityId)
// so a requested permission like "varwof/demo-mysql-v1:SELECT:*" matches an AIC declaration
// of {SchemeId:"varwof/demo-mysql-v1", CapabilityId:"SELECT:*"}.
func (a *AIC) CheckPermission(required string) bool {
	if a == nil {
		return false
	}
	for _, cap := range a.Capabilities {
		if MatchCapability(cap.FullID(), required) {
			return true
		}
	}
	return false
}

// IntersectPermissions returns the CapabilityId intersection between AIC capabilities and PrincipalAuthorization grants.
func (a *AIC) IntersectPermissions(pa *PrincipalAuthorization) []string {
	if a == nil || pa == nil {
		return nil
	}
	return a.IntersectPermissionsStr(pa.GrantIds())
}

// IntersectPermissionsStr returns AIC capabilities (full IDs) that match any
// pattern in upPerms (glob). Matching is on FullID so a PA grant of
// {SchemeId:"varwof/demo-mysql-v1", CapabilityId:"SELECT:*"} covers an AIC declaration of
// {SchemeId:"varwof/demo-mysql-v1", CapabilityId:"SELECT:/api/tables"}.
func (a *AIC) IntersectPermissionsStr(upPerms []string) []string {
	if a == nil || len(a.Capabilities) == 0 || len(upPerms) == 0 {
		return nil
	}
	seen := make(map[string]bool)
	var result []string
	for _, c := range a.Capabilities {
		for _, p := range upPerms {
			if !seen[c.FullID()] && MatchCapability(c.FullID(), p) {
				seen[c.FullID()] = true
				result = append(result, c.FullID())
			}
		}
	}
	return result
}

// IntersectPermissionsStrAny parses a comma/space-delimited string and returns intersection.
func (a *AIC) IntersectPermissionsStrAny(upPerms string) []string {
	if a == nil || upPerms == "" {
		return nil
	}
	var perms []string
	for _, s := range strings.FieldsFunc(upPerms, func(r rune) bool {
		return r == ',' || r == ' '
	}) {
		if s != "" {
			perms = append(perms, s)
		}
	}
	return a.IntersectPermissionsStr(perms)
}

// MatchCapability checks if id matches pattern, supporting `*`/`?`/`**` glob syntax.
func MatchCapability(id, pattern string) bool {
	if id == pattern {
		return true
	}
	if pattern == "**" || pattern == "*" {
		return true
	}
	if ok, _ := path.Match(pattern, id); ok {
		return true
	}
	if strings.Contains(pattern, "**") {
		return matchDoubleStar(id, pattern)
	}
	return false
}

func matchDoubleStar(id, pattern string) bool {
	parts := strings.Split(pattern, "**")
	if len(parts) != 2 {
		return false
	}
	prefix := strings.TrimRight(parts[0], "/")
	suffix := strings.TrimLeft(parts[1], "/")

	remaining := id
	if prefix != "" {
		if !strings.HasPrefix(remaining, prefix) {
			return false
		}
		remaining = strings.TrimPrefix(remaining, prefix)
		remaining = strings.TrimPrefix(remaining, "/")
	}
	if suffix != "" {
		if !strings.HasSuffix(remaining, suffix) {
			return false
		}
		remaining = strings.TrimSuffix(remaining, suffix)
		remaining = strings.TrimSuffix(remaining, "/")
	}
	if remaining == "" {
		return true
	}
	for _, seg := range strings.Split(remaining, "/") {
		if seg == "" || seg == ".." {
			return false
		}
	}
	return true
}

// ValidateAIC validates AIC field constraints per v1.7.1 spec (03-validation.md).
func ValidateAIC(aic *AIC) error {
	if aic == nil {
		return nil
	}
	if len(aic.AgentId) < 1 || len(aic.AgentId) > 256 {
		return fmt.Errorf("aic: agentId length %d: must be 1-256", len(aic.AgentId))
	}
	if len(aic.Capabilities) > MaxCapabilities {
		return fmt.Errorf("aic: capabilities count %d exceeds max %d", len(aic.Capabilities), MaxCapabilities)
	}
	for i, cap := range aic.Capabilities {
		if len(cap.SchemeId) < 1 || len(cap.SchemeId) > 128 {
			return fmt.Errorf("aic: capability[%d].schemeId length %d: must be 1-128", i, len(cap.SchemeId))
		}
		if len(cap.CapabilityId) < 1 || len(cap.CapabilityId) > 256 {
			return fmt.Errorf("aic: capability[%d].capabilityId length %d: must be 1-256", i, len(cap.CapabilityId))
		}
		if len(cap.Parameters) > MaxCapParams {
			return fmt.Errorf("aic: capability[%d].parameters length %d: must be 0-%d", i, len(cap.Parameters), MaxCapParams)
		}
		// V15: capabilities MUST NOT use the constraint scheme.
		if cap.SchemeId == "varwof/constraint-v1" {
			return fmt.Errorf("aic: capability[%d].schemeId %q: constraint scheme forbidden in capabilities", i, cap.SchemeId)
		}
	}
	// V16: extensions slot capacity limit is 32 (spec P1-A-08).
	if len(aic.Extensions) > MaxExtensionsSlots {
		return fmt.Errorf("aic: extensions count %d exceeds max %d", len(aic.Extensions), MaxExtensionsSlots)
	}
	for i, ext := range aic.Extensions {
		if ext.Critical && !isKnownExtension(ext.ExtnID) {
			return fmt.Errorf("aic: extensions[%d] has unknown critical OID %v", i, ext.ExtnID)
		}
	}
	// V6: keyHash length must equal hashAlgo output length (SHA-256/SM3 = 32).
	if len(aic.PrincipalUid.Realm) < 1 || len(aic.PrincipalUid.Realm) > 128 {
		return fmt.Errorf("aic: principalUid.realm length %d: must be 1-128", len(aic.PrincipalUid.Realm))
	}
	if len(aic.PrincipalUid.Identifier) < 1 || len(aic.PrincipalUid.Identifier) > 256 {
		return fmt.Errorf("aic: principalUid.identifier length %d: must be 1-256", len(aic.PrincipalUid.Identifier))
	}
	if err := ValidatePrincipalUidKeyHash(aic.PrincipalUid); err != nil {
		return err
	}
	da := aic.DelegationAuthorization
	if !da.IsPresent() {
		return fmt.Errorf("aic: delegationAuthorization is required but missing")
	}
	// R1/R2: reason fields MUST exist and be non-empty.
	if da.Reason.ReasonCode == "" {
		return fmt.Errorf("aic: delegationAuth.reason.reasonCode: must not be empty")
	}
	if da.Reason.Description == "" {
		return fmt.Errorf("aic: delegationAuth.reason.description: must not be empty")
	}
	// R4/R5: reason length bounds.
	if len(da.Reason.ReasonCode) > 64 {
		return fmt.Errorf("aic: delegationAuth.reason.reasonCode length %d: must be <= 64", len(da.Reason.ReasonCode))
	}
	if len(da.Reason.Description) > 512 {
		return fmt.Errorf("aic: delegationAuth.reason.description length %d: must be <= 512", len(da.Reason.Description))
	}
	if len(da.Nonce) != MaxNonceLen {
		return fmt.Errorf("aic: delegationAuth.nonce length %d: must be exactly %d bytes", len(da.Nonce), MaxNonceLen)
	}
	// V8: requestedLifetime 1..86400 (SHOULD >= 3600); 0 is upgraded to 3600.
	lifetime := da.RequestedLifetime
	if lifetime == 0 {
		lifetime = MinRequestedLifetime
	}
	if lifetime < 1 || lifetime > MaxRequestedLifetime {
		return fmt.Errorf("aic: delegationAuth.requestedLifetime %d: must be 1-%d", da.RequestedLifetime, MaxRequestedLifetime)
	}
	if len(aic.AuthorizationConstraints) > MaxAuthorizationConstraints {
		return fmt.Errorf("aic: authorizationConstraints count %d exceeds max %d", len(aic.AuthorizationConstraints), MaxAuthorizationConstraints)
	}
	for i, c := range aic.AuthorizationConstraints {
		// V10: constraint schemeId whitelist.
		if c.SchemeId != "constraint" && c.SchemeId != "constraint-v1" && c.SchemeId != "varwof/constraint-v1" {
			return fmt.Errorf("aic: authorizationConstraints[%d].schemeId %q: must be \"constraint\", \"constraint-v1\", or \"varwof/constraint-v1\"", i, c.SchemeId)
		}
		if len(c.CapabilityId) == 0 {
			return fmt.Errorf("aic: authorizationConstraints[%d].capabilityId: must not be empty", i)
		}
		if len(c.Parameters) > MaxConstraintParams {
			return fmt.Errorf("aic: authorizationConstraints[%d].parameters length %d: must be 0-%d", i, len(c.Parameters), MaxConstraintParams)
		}
		if len(c.Parameters) > 0 && !json.Valid(c.Parameters) {
			return fmt.Errorf("aic: authorizationConstraints[%d].parameters: invalid JSON", i)
		}
		// V17: max-concurrent constraint parameters must be {"max": N} with N in 1..1024 (spec P1-A-29).
		if c.CapabilityId == ConstraintConcurrentKey && len(c.Parameters) > 0 {
			if err := ValidateMaxConcurrentParam(c.Parameters); err != nil {
				return fmt.Errorf("aic: authorizationConstraints[%d]: %v", i, err)
			}
		}
	}
	return nil
}

// ValidatePrincipalUidKeyHash validates the keyHash length against the declared hashAlgo.
// Per v1.7.1 the spec supports hash algorithms with output length <= 64 bytes
// (keyHash OCTET STRING SIZE(1..64)). SHA-2/SHA-3 family implemented by stdlib + SM3
// built-in pure Go implementation (C1) with length validation; BLAKE2/BLAKE3 and other
// algorithms requiring external dependencies return explicit errors (never silently fallback to SHA-256).
func ValidatePrincipalUidKeyHash(pu PrincipalUid) error {
	if len(pu.KeyHash) == 0 {
		return fmt.Errorf("aic: principalUid.keyHash: required")
	}
	algo := pu.HashAlgoOID()
	if len(algo) == 0 {
		algo = OIDSHA256
	}
	name := HashOIDName(algo)
	if name == "" {
		return fmt.Errorf("aic: principalUid.hashAlgo %v: unsupported keyHash algorithm", algo)
	}
	want, ok := HashOutputLen[name]
	if !ok {
		return fmt.Errorf("aic: principalUid.hashAlgo %v: no output length mapping (requires external dependency)", algo)
	}
	if len(pu.KeyHash) != want {
		return fmt.Errorf("aic: principalUid.keyHash length %d: must be %d (%s)", len(pu.KeyHash), want, name)
	}
	return nil
}

func isKnownExtension(oid asn1.ObjectIdentifier) bool {
	known := []asn1.ObjectIdentifier{
		{1, 3, 6, 1, 4, 1, 66257, 1, 1, 1}, // AgentIdentity
		{1, 3, 6, 1, 4, 1, 66257, 1, 1, 2}, // DelegationAuthorization
		{1, 3, 6, 1, 4, 1, 66257, 1, 2},    // PrincipalAuthorization
		{1, 3, 6, 1, 4, 1, 66257, 3, 1},    // MarketAccessId
	}
	for _, k := range known {
		if oid.Equal(k) {
			return true
		}
	}
	return false
}

// SigAlgoToOID maps x509.SignatureAlgorithm to AlgorithmIdentifier.
func SigAlgoToOID(algo x509.SignatureAlgorithm) AlgorithmIdentifier {
	switch algo {
	case x509.ECDSAWithSHA256:
		return AlgorithmIdentifier{Algorithm: OIDSigECDSAWithSHA256}
	case x509.ECDSAWithSHA384:
		return AlgorithmIdentifier{Algorithm: OIDSigECDSAWithSHA384}
	case x509.ECDSAWithSHA512:
		return AlgorithmIdentifier{Algorithm: OIDSigECDSAWithSHA512}
	case x509.SHA256WithRSA:
		return AlgorithmIdentifier{Algorithm: OIDSigRSAWithSHA256}
	case x509.SHA384WithRSA:
		return AlgorithmIdentifier{Algorithm: OIDSigRSAWithSHA384}
	case x509.SHA512WithRSA:
		return AlgorithmIdentifier{Algorithm: OIDSigRSAWithSHA512}
	case x509.PureEd25519:
		return AlgorithmIdentifier{Algorithm: OIDSigEd25519}
	default:
		return AlgorithmIdentifier{}
	}
}

var _ = pkix.Extension{}

// ValidateMaxConcurrentParam validates max-concurrent constraint parameters ({"max": N},
// N in 1..1024, spec P1-A-29). Missing/empty parameters return nil (not configured).
func ValidateMaxConcurrentParam(raw []byte) error {
	trimmed := bytes.TrimSpace(raw)
	if len(trimmed) == 0 {
		return nil
	}
	var obj struct {
		Max int `json:"max"`
	}
	if err := json.Unmarshal(trimmed, &obj); err != nil {
		return fmt.Errorf("max-concurrent: invalid JSON: %v", err)
	}
	if obj.Max < MaxConcurrentMin || obj.Max > MaxConcurrentMax {
		return fmt.Errorf("max-concurrent: max %d: must be %d-%d", obj.Max, MaxConcurrentMin, MaxConcurrentMax)
	}
	return nil
}

// SPIFFE constants and helpers for optional SPIFFE identity integration.

const (
	// SPIFFEScheme is the URI scheme for SPIFFE identities.
	SPIFFEScheme = "spiffe"
	// SPIFFEAgentPrefix is the standard path prefix for agent workloads.
	SPIFFEAgentPrefix = "/agent/"
)

// BuildSPIFFEID constructs a SPIFFE ID from trust domain and agent name.
// Returns "spiffe://{trustDomain}/agent/{agentName}".
func BuildSPIFFEID(trustDomain, agentName string) string {
	return fmt.Sprintf("spiffe://%s/agent/%s", trustDomain, agentName)
}

// ValidateSPIFFEID checks that id matches the expected format:
// "spiffe://{trustDomain}/agent/{name}" where name is non-empty.
func ValidateSPIFFEID(id, trustDomain string) error {
	prefix := fmt.Sprintf("spiffe://%s/agent/", trustDomain)
	if !strings.HasPrefix(id, prefix) {
		return fmt.Errorf("spiffe: invalid ID %q: must start with %s", id, prefix)
	}
	name := strings.TrimPrefix(id, prefix)
	if name == "" {
		return fmt.Errorf("spiffe: invalid ID %q: agent name is empty", id)
	}
	if strings.Contains(name, "/") {
		return fmt.Errorf("spiffe: invalid ID %q: agent name must not contain /", id)
	}
	return nil
}

// ExtractSPIFFEIDFromCert extracts the SPIFFE ID from a certificate's SAN URIs.
// Returns empty string if no SPIFFE URI is found.
func ExtractSPIFFEIDFromCert(cert *x509.Certificate) string {
	if cert == nil {
		return ""
	}
	for _, uri := range cert.URIs {
		if uri.Scheme == SPIFFEScheme {
			return uri.String()
		}
	}
	return ""
}

// IsSPIFFEAgentID returns true if the agentId is in SPIFFE format.
func IsSPIFFEAgentID(agentId string) bool {
	return strings.HasPrefix(agentId, "spiffe://")
}

// ParseSPIFFEAgentName extracts the agent name from a SPIFFE agentId.
// "spiffe://varwof.com/agent/scheduler-a" → "scheduler-a"
// Returns the original id if it's not in SPIFFE format.
func ParseSPIFFEAgentName(agentId string) string {
	if !IsSPIFFEAgentID(agentId) {
		return agentId
	}
	idx := strings.LastIndex(agentId, "/")
	if idx < 0 {
		return agentId
	}
	return agentId[idx+1:]
}

// ParseSPIFFEDomain extracts the trust domain from a SPIFFE agentId.
// "spiffe://varwof.com/agent/scheduler-a" → "varwof.com"
// Returns empty string if not in SPIFFE format.
func ParseSPIFFEDomain(agentId string) string {
	if !IsSPIFFEAgentID(agentId) {
		return ""
	}
	trimmed := strings.TrimPrefix(agentId, "spiffe://")
	idx := strings.Index(trimmed, "/")
	if idx < 0 {
		return ""
	}
	return trimmed[:idx]
}

// AddSPIFFESANToCert adds a SPIFFE URI to a certificate's SAN URIs.
// Does not add if the SPIFFE ID already exists.
func AddSPIFFESANToCert(cert *x509.Certificate, spiffeID string) error {
	u, err := url.Parse(spiffeID)
	if err != nil {
		return fmt.Errorf("spiffe: invalid URI %q: %v", spiffeID, err)
	}
	if u.Scheme != SPIFFEScheme {
		return fmt.Errorf("spiffe: URI scheme must be %q, got %q", SPIFFEScheme, u.Scheme)
	}
	// Deduplicate
	for _, existing := range cert.URIs {
		if existing.String() == u.String() {
			return nil
		}
	}
	cert.URIs = append(cert.URIs, u)
	return nil
}
